# Generated by Django 6.0.4 on 2026-05-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneModeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='시나리오 제목')),
                ('summary', models.TextField(verbose_name='시나리오 개요')),
                ('keyword1', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드 1')),
                ('keyword2', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드 2')),
                ('keyword3', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드 3')),
                ('default_personality', models.TextField(verbose_name='기본 성격')),
                ('default_identity', models.TextField(verbose_name='기본 정체성')),
                ('default_values', models.TextField(verbose_name='기본 가치관')),
                ('default_first_scene', models.TextField(verbose_name='첫 장면 상황 설명')),
            ],
            options={
                'verbose_name': '역할극 시나리오 정보',
                'verbose_name_plural': '역할극 시나리오 정보 목록',
                'db_table': 'scene_mode_info',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SceneCharInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='캐릭터 이름')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='캐릭터 키워드(성격 등)')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='캐릭터 한 줄 요약 및 설명')),
                ('is_extra', models.BooleanField(blank=True, default=False, verbose_name='캐릭터 역할')),
                ('img_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='프로필 이미지 URL')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='scenarios.scenemodeinfo', verbose_name='소속 스토리')),
            ],
            options={
                'verbose_name': '역할극 캐릭터 정보',
                'verbose_name_plural': '역할극 캐릭터 정보 목록',
                'db_table': 'scene_char_info',
            },
        ),
        migrations.CreateModel(
            name='SceneRoomSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_len', models.CharField(choices=[('short', 'Short'), ('normal', 'Normal'), ('long', 'Long'), ('very_long', 'Very Long')], default='normal', max_length=20, verbose_name='답변 길이 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_room', to='characters.charpersona', verbose_name='적용된 페르소나 ID')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scenarios.scenemodeinfo', verbose_name='시나리오 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_rooms', to='users.user', verbose_name='사용자 ID')),
            ],
            options={
                'verbose_name': '역할극 채팅방 설정',
                'verbose_name_plural': '역할극 채팅방 설정 목록',
                'db_table': 'scene_room_settings',
            },
        ),
        migrations.CreateModel(
            name='SceneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scene', 'Scene'), ('user', 'User'), ('character', 'Character')], max_length=20, verbose_name='메시지 타입')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('char', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='scenarios.scenecharinfo', verbose_name='발화 캐릭터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_messages', to='users.user', verbose_name='사용자 ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scenarios.sceneroomsetting', verbose_name='채팅방 ID')),
            ],
            options={
                'verbose_name': '역할극 채팅 메시지',
                'verbose_name_plural': '역할극 채팅 메시지 목록',
                'db_table': 'scene_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
